### PR TITLE
the style of card & the layout of  zaa-image-array-upload

### PR DESCRIPTION
**Pull request by baqianxin**
Excuse me, How do I rebase onto the master branch?

### CODE REVIEW

**Comment by nadar** [comment]
@baqianxin You should provide at least a screenshot or a reason of why we should change / update the current styles?

**Comment by nadar** [comment]
@baqianxin Maybe we should talk first about what this changes introduce and why, instead of pushing more commits to it.

**Comment by baqianxin** [comment]
image
image

**Comment by baqianxin** [comment]
i agree with you

**Comment by baqianxin** [comment]
and i want add the ChartDashboardObject

**Comment by nadar** [comment]
@baqianxin your pull requests is not structured. sorry we can not accept this PR as you are just committing into this pull request. You have to make several branches you can pull request.

Maybe should read a bit in the help section of github => https://help.github.com/articles/creating-a-pull-request/

**Comment by baqianxin** [comment]
like this!

**Comment by baqianxin** [comment]
OK，i  got it ，

**Pull request closed without merging**
