### PR TITLE
Toggle button for ngRestModel

### PR DESCRIPTION
**Pull request by boehsermoe**
Toggle a value between active and inactive. Also can keep a active status unique for a table.

### CODE REVIEW

**Comment by nadar** [comment]
This is a very good idea, the only draw back against ngrest toggle status is that it contains no scheduling, but an option to make the checkbox unique is very usefull and also something we could use in admin lang ngrest table.

Let me know if its ready for review, don't forget to add a PR :-) thanks

**Comment by boehsermoe** [comment]
@nadar What do you mean with "scheduling"?

**Comment by nadar** [comment]
They NgRest Plugin: "ToggleStatus" does have the option to schedule the time of toggling. (since admin 2.0 with new scheduler system).

**Comment by boehsermoe** [comment]
For the first there is no more for the theme topic in the admin module. Only this new action button.
The rest is in the cms module.

**Comment by nadar** [comment]
Hey @boehsermoe i am looking forward to merge this, i just saw that not all lines are covered by the unit test. not uniqueStatus for example, and setting an active value. Do you think its possible to add those? Thanks a lot

**Comment by boehsermoe** [comment]
@nadar yes of course.

**Pull request merged**
