### PR TITLE
Fixed placeholders in translations

### PR DESCRIPTION
**Pull request by hbugdoll**
### What are you changing/introducing

Fixed parameter placeholders in Dutch, Hungarian and Polish translations for`Yii::t()`.

### What is the reason for changing/introducing

Parameter placeholder names were accidentally translated, e.g. `{attempt}` &rarr; `{kísérlet}`
or have wrong camel-case, e.g. `{{idleTimeRelative}}` &rarr; `{{idleTimereLative}}`.

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | –

### CODE REVIEW

**Comment by hbugdoll** [comment]
I will check the failing tests...

**Comment by nadar** [comment]
this failing tests is due to a date usage which needs to changed by the 1.1. of each year. I can fix that

**Comment by hbugdoll** [comment]
> this failing tests is due to a date usage which needs to changed by the 1.1. of each year.

Good to know.
I've found it right now... `54 years` vs. `53 years` in the test output.

> I can fix that

Thank you.

**Comment by nadar** [comment]
> I've found it right now... 54 years vs. 53 years in the test output.

yes perfect, could you not please adjust it along with your changes? would be great, thanks!

**Comment by nadar** [comment]
Thanks!

**Pull request merged**
