### PR TITLE
admin.php

### PR DESCRIPTION
**Pull request by testt23**
Bulgarian language

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by nadar** [comment]
It seems there is a translation key missing:

```
The language key 'api_sotrage_file_upload_empty_error' does not exists in the language file '/home/runner/work/luya-module-admin/luya-module-admin/src/messages/bg/admin.php'.
Failed asserting that an array has the key 'api_sotrage_file_upload_empty_error'.
```

**Review by nadar — CHANGES_REQUESTED** [review]
The language key 'api_sotrage_file_upload_empty_error' does not exists in the language file '/home/runner/work/luya-module-admin/luya-module-admin/src/messages/bg/admin.php'.
Failed asserting that an array has the key 'api_sotrage_file_upload_empty_error'.

**Review by testt23 — COMMENTED** [review]
I corrected omitted lines.

**Comment by nadar** [comment]
Thanks

**Review by nadar — APPROVED** [review]

**Pull request merged**
