### PR TITLE
add Chinese message

### PR DESCRIPTION
**Pull request by baqianxin**
add the chinese messages

### CODE REVIEW

**Comment by baqianxin** [comment]
OK，I'll try again in English.But I do not know how to add an changelog @

**Comment by nadar** [comment]
Just add your changes here: https://github.com/luyadev/luya-module-admin/blob/master/CHANGELOG.md

Like

```
+ [#34](https://github.com/luyadev/luya-module-admin/pull/34#issuecomment-354948943) Added chinese translations
```

**Comment by nadar** [comment]
You should commit here, like github already says

> Add more commits by pushing to the luya-chinese-oom branch on baqianxin/luya-module-admin.

There you have to add the changelog commit, in `luya-chinese-oom` branch of your fork. Then it will be auto added to this PR.

**Comment by baqianxin** [comment]
I can not delete the previous commits.

**Pull request merged**
