### PR TITLE
Thai language translation

### PR DESCRIPTION
**Pull request by naiiytom**
### What are you changing/introducing
Add **thai** language translation
some words are specific terms, so couldn't be translated

issue
https://github.com/luyadev/luya/issues/1159

### CODE REVIEW

**Comment by nadar** [comment]
Thank you very much, in order to merge the admin PR, we also need a PR for core and CMS, which is "minimal" requirement for a new language.

See the quote from issue https://github.com/luyadev/luya/issues/1159:

> For upcoming translators, those files must at least be translated in order to get integrated into the admin interface:
> Admin: https://github.com/luyadev/luya-module-admin/tree/master/src/messages
> CMS Frontend: https://github.com/luyadev/luya-module-cms/tree/master/src/frontend/messages
> CMS Admin: https://github.com/luyadev/luya-module-cms/tree/master/src/admin/messages

**Comment by naiiytom** [comment]
Okay, I will also do the remainings then.

**Comment by nadar** [comment]
Nice, so i will wait for the other two requests until i can merge.

**Comment by nadar** [comment]
Let me know if you need help

**Comment by naiiytom** [comment]
Alright, I'm working on it.

**Comment by nadar** [comment]
Thanks!

**Pull request merged**
