### PR TITLE
Fix for multiple radio fields

### PR DESCRIPTION
**Pull request by hbugdoll**
fixed https://github.com/luyadev/luya-module-cms/issues/308

### CODE REVIEW

**Review by nadar — CHANGES_REQUESTED** [review]
@TheMaaarc was it that simple? 
@hbugdoll please add a changelog, but @TheMaaarc will check for approval.

**Comment by hbugdoll** [comment]
### What are you changing

`name` attribute of `<input type="radio" ...>` in directive **zaaRadio**

### What is the reason for changing

Checked radio buttons in multiple radio fields (e.g. in CMS blocks) aren't displayed correctly.

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | luyadev/luya-module-cms#308

**Comment by hbugdoll** [comment]
I'm not sure about your processing of JS files for the distribution folder `dist`.

Maybe the commit https://github.com/hbugdoll/luya-module-admin/commit/e698902b0e12b5a3c6b11bd7b53798f8ce2a3c32 (change of`dist/main.js`) should be also added to this PR.

**Comment by nadar** [comment]
We will compile the files after merge

**Comment by nadar** [comment]
by "changelog entry" i meant adding this pr to => https://github.com/luyadev/luya-module-admin/blob/master/CHANGELOG.md

**Comment by hbugdoll** [comment]
> We will compile the files after merge

Thanks for this clarification.

> by "changelog entry" i meant adding this pr to => https://github.com/luyadev/luya-module-admin/blob/master/CHANGELOG.md

Sorry, misunderstood...

**Review by TheMaaarc — APPROVED** [review]
Nice! 👌

**Review by nadar — APPROVED** [review]

**Pull request merged**
